M48
; DRILL file {KiCad (6.0.10)} date Sat Jan 14 14:38:55 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-14T14:38:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X114.3Y-78.74
X114.3Y-91.44
X134.62Y-78.74
X134.62Y-91.44
T0
M30
